version: '3.7'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse_server
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
      - ./migrations:/docker-entrypoint-initdb.d
